program: train.py

project: bert-sentiment-analysis
method: bayes

description: "Bert sweep"

metric:
  name: val/acc
  goal: maximize

parameters:
  model.lr:
    distribution: uniform
    min: 0.00001
    max: 0.0005
  datamodule.batch_size:
    values: [16]
  model.weight_decay:
    distribution: uniform
    min: 0.0001
    max: 0.01

early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 2

command:
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
  - logger=wandb